### ISSUE TITLE
can you add google maps also

### ISSUE THREAD

**Issue by ghost** [SvenTiigi/FlyoverKit#5]
Can you add google maps also

**Comment by SvenTiigi** [comment]
Hey @pprevalon,

thanks for you feature request 🙌

IMHO the requested feature should be considered in a separated fork of `FlyoverKit`. Something like `FlyoverKit+GoogleMaps`.

Adding the feature in `FlyoverKit` itself would result that every developer who uses `FlyoverKit` will need to embed the `Google Maps SDK` in their application, which isn't the best way of creating a Swift Library.

Please feel free to fork `FlyoverKit` in order to start an implementation for the `Google Maps SDK` 👌
